[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F9F9F9"
textColor = "#333333"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
